on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run:  sudo apt-get install -y speech-dispatcher libspeechd-dev
      - name: Install deepspeech native client
        run: wget --no-check-certificate https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/native_client.amd64.cpu.linux.tar.xz
        run: pwd
        run: ls
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Building corporate-assistant
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release




