on: [pull_request]

name: Continuous integration

jobs:

  fmt:
     name: Rustfmt
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions-rs/toolchain@v1
         with:
           profile: minimal
           toolchain: stable
           override: true
       - run: rustup component add rustfmt
       - uses: actions-rs/cargo@v1
         with:
           command: fmt
           args: --all -- --check

  build_and_test:
      name: corporate-assistant building
      runs-on: ubuntu-latest
      steps:
        - name: Install system dependencies
          run:  sudo apt-get install -y speech-dispatcher libspeechd-dev libsdl2-dev
        - name: Install deepspeech native client
          env:
            LIBRARY_PATH: ./
          run: |
            wget --no-check-certificate https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/native_client.amd64.cpu.linux.tar.xz
            pwd
            tar -xJf  native_client.amd64.cpu.linux.tar.xz
            ls
            echo "LIBRARY_PATH: $LIBRARY_PATH"
        - uses: actions/checkout@v2
        - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
        - name: Cargo build
          env:
            LIBRARY_PATH: ./
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --release --all-features
