on: [push, pull_request]

name: Continuous integration

jobs:

  fmt:
     name: Rustfmt
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - uses: actions-rs/toolchain@v1
         with:
           profile: minimal
           toolchain: stable
           override: true
       - run: rustup component add rustfmt
       - uses: actions-rs/cargo@v1
         with:
           command: fmt
           args: --all -- --check

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run:  sudo apt-get install -y speech-dispatcher libspeechd-dev
      - name: Install deepspeech native client
        run: |
          wget --no-check-certificate https://github.com/mozilla/DeepSpeech/releases/download/v0.9.3/native_client.amd64.cpu.linux.tar.xz
          pwd
          ls
          tar -xJf  native_client.amd64.cpu.linux.tar.xz
          #- env:
          #LIBRARY_PATH: $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check

