on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run:  sudo apt-get install -y speech-dispatcher libspeechd-dev
      - env:
        LIBRARY_PATH: $GITHUB_WORKSPACE
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Building corporate-assistant
      - uses: actions-rs/cargo@v1
          command: build
          args: --release




